### PR TITLE
Lina's notes for lecture 6

### PR DESCRIPTION
**Pull request by yuqingtian**
Here are the files for lecture 6 from yt2511

### CODE REVIEW

**Comment by redouane-dziri** [comment]
Hi Lina, please pull again from the repository, remove the .DS_Store files and produce your notes in template.pdf so that you show you checked it compiled as expected

**Comment by yuqingtian** [comment]
.DS_store file removed and template.pdf added

**Comment by redouane-dziri** [comment]
There are still two .DS_Store files in the outside folders, and please pull before resubmitting the pull request (you are missing a lot of the lecture folders)

**Comment by yuqingtian** [comment]
Sorry, did not realize there were more .DS_Store files, should be all deleted

**Comment by redouane-dziri** [comment]
please pull before repushing and resubmitting the pull request (you are missing a lot of the lecture folders)

**Comment by redouane-dziri** [comment]
(or maybe easier to re-fork the repo - make sure you have all lecture folders - and copy and paste your lecture 6 folder in, push and pull request)

**Pull request merged**
