### PR TITLE
lecture10notes

### PR DESCRIPTION
**Pull request by brigid450**

### CODE REVIEW

**Comment by redouane-dziri** [comment]
pull from the repository to update it (git pull origin master) and re-submit your pull request after checking that your lecture 10 folders contains 2 subfolders
your lecture 10 folder is missing the subfolder from gia2105

**Comment by brigid450** [comment]
Hi! I updated the repository but the file still isn’t there. I can’t see
any commits by gia2015 on the repository page.
Thanks!

**Comment by redouane-dziri** [comment]
You can't see it here: https://github.com/jhofman/msd2019-notes ?
I remember seeing it yesterday at OH when we forked the repo together

**Comment by brigid450** [comment]
I think I fixed it! Let me know if this works! (Sorry for all the back and forth I'm v new to this)

**Comment by redouane-dziri** [comment]
Looks good! (No worries, been there!)

**Pull request merged**
