### PR TITLE
updated scribe notes for lecture 7

### PR DESCRIPTION
**Pull request by smarshy**
scribe notes for lecture 7

### CODE REVIEW

**Comment by redouane-dziri** [comment]
looks good, just re-pull from the repo as one pull request has been merged since you last pulled, and re-submit your pull request (should have three subfiles in lecture_7)

**Comment by smarshy** [comment]
@redouane-dziri Sorry to have missed this earlier, Have updated this PR with all the latest commits in this repository.

**Comment by redouane-dziri** [comment]
just re-pull from the repo as one pull request from lecture 8 has been merged since you last pulled, and re-submit your pull request (should have two subfolders in lecture_8)!

**Comment by smarshy** [comment]
@redouane-dziri Done

**Pull request merged**
