### PR TITLE
add mzf2106 lecture 4 notes to master branch

### PR DESCRIPTION
**Pull request by miazfryer**
created lecture_4 folder as well as mzf2106 folder and populated with my lecture notes for lecture 4 and figures for the .tex document

### CODE REVIEW

**Comment by redouane-dziri** [comment]
please refactor your tex documents so that you have template.tex and mzf2106.tex to make it easier to merge notes from different people (look at previous weeks for reference)

**Comment by redouane-dziri** [comment]
you still need to modify template.tex and mzf2106.tex 
look at other weeks for examples

**Comment by miazfryer** [comment]
the only thing I see to modify as adding the mzf2106.tex to the input on the template / notes 
is there something else I am missing?

**Comment by redouane-dziri** [comment]
Yes, your name and date and lecture title in template.tex, and remove most of the introductory latex statements in your file mzf2106.tex. Again, look at others for reference.

**Comment by redouane-dziri** [comment]
Nearly there! Now generate the template.pdf from your template.tex to check that everything compiles correctly and push it

**Comment by redouane-dziri** [comment]
review the content of your folder, something's not right.. template.pdf.pdf

**Comment by miazfryer** [comment]
should be good now

**Pull request merged**
